CREATE TABLE EMPLOYEES
   (	EMP_ID NUMBER,
	NAME VARCHAR2(100),
	DEPT_ID NUMBER,
	DEPT_ALT_ID NUMBER,
	 PRIMARY KEY (EMP_ID)
  USING INDEX  ENABLE,
	 CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID)
	  REFERENCES DEPARTMENTS (DEPT_ID) ENABLE
   ) ;

